### ISSUE TITLE
Ctr-Z doesn't undo last action

### ISSUE THREAD

**Issue by Vilhelm-Ian** [mortii/anki-morphs#15]
I pressed K on a card. And wanted to double check if I knew the word and i wasn't able with ctrl+z

**Comment by mortii** [comment]
Yeah, that is the "Fix undo-review" item on the [roadmap](https://mortii.github.io/anki-morphs/user_guide/roadmap.html).

**Comment by mortii** [comment]
I'm making good progress on this. My previous assessment (https://github.com/kaegi/MorphMan/issues/302)  was pessimistic, but I found an amazing [ankiweb thread](https://forums.ankiweb.net/t/add-on-porting-notes-for-anki-2-1-45/11212#undoredo-4) that has made it much easier.

One caveat is that the new undo system only works for the v3 scheduler, but that is actually a blessing in disguise because I can now stop supporting v2 and just display an error if someone is using it.

**Comment by mortii** [comment]
My pessimism was warranted, fixing this was a nightmare, lol. There is [a known bug](https://mortii.github.io/anki-morphs/user_guide/known-problems.html#set-known-and-skip) I can't fix, but it should be rare enough to not cause any major problems. One thing to keep in mind is that the undo queue breaks/is reset after a recalc.

**Comment by mortii** [comment]
Let me know if any other problems occur!
