### ISSUE TITLE
Consider only the cloze part of the card known

### ISSUE THREAD

**Issue by aleksejrs** [mortii/anki-morphs#153]
**Is your feature request related to a problem? Please describe.**
All words in the field with cloze deletions become "known", but only the cloze part is the one you remember.

**Describe the solution you'd like**
Known morphs should be taken only from the cloze parts.
Unknown morphs (and morphs seen today) should still be taken from the whole field.

It is, of course, much better if a cloze deletion is considered only in relation to its card, so that if there are two cards and one of them is mature and the other one is new, only the morphs in the mature one's cloze deletion become known.

**Comment by mortii** [comment]
Sorry, but no, I stand by my previous answer:

> @aleksejrs I now think that this feature would be overfitting and too detrimental to the overall algorithm unfortunately, so I won't be implementing this, sorry :slightly_frowning_face:

_Originally posted by @mortii in https://github.com/mortii/anki-morphs/discussions/12#discussioncomment-7983313_

I'll elaborate further:

1. I think there are already too many note-filter options, it's a mess.
2. The morph caching is already very complicated and slow. This would make it exponentially worse. This problem is self-evident if you look at the caching code, which I encourage you to do.

I think this feature is  _hyper_ specific to your use-case and won't be widely used, so it would not be worth it to exacerbate to issues I outline above.

Sorry.

**Comment by aleksejrs** [comment]
What if it reads with a morphemizer that only extracts the close part, and writes with the normal one?
