### ISSUE TITLE
Frequencylist doesn't work for me with Spanish

### ISSUE THREAD

**Issue by SalomoDavidson** [mortii/anki-morphs#238]
### Describe the bug
The frequencylist doesn't order my deck when I press on recall. I don't understand what I do wrong. I use the Spanish list. Everything in the settings seems fine.

![image](https://github.com/mortii/anki-morphs/assets/61660028/e8c84d51-0314-4755-9b16-77c8cf643f86)

 - Operating System: Windows 11
 - Anki Version: 23.12.1
 - AnkiMorphs Version: 2.00

**Comment by mortii** [comment]
> The frequencylist doesn't order my deck when I press on recall.

1. Does the deck contain cards with the note types you selected in the AnkiMorphs settings? 
2. Does it have sub-decks? If so, have you changed the [deck options](https://mortii.github.io/anki-morphs/user_guide/setup/decks.html#deck-options)?
3. Does it work if you use "Collection frequency" instead of the "es-freq.csv" file?

**Comment by SalomoDavidson** [comment]
1. Yes it does,
2. No it doesn't.
3. Does that work? I only use the target word not the sentence. So every word is used one time.

**Comment by mortii** [comment]
> 3\. Does that work? I only use the target word not the sentence. So every word is used one time.

Sorry, I was too vague. That was just a test for if your cards are reordered at all when you select something else.

If you are willing to share your card collection then I can probably figure out the problem quickly. I would need these two things:
1. There is a "collection.anki2" file in the anki profile folder, upload it to google drive or some other place I could download it
2. Go to "Tools" -> "Add-ons" -> Select "AnkiMorphs" -> click the "Config" button on the lower right side -> copy paste the info here.

**Comment by SalomoDavidson** [comment]
Ah oké, the cards are reordered but not in order of the frequencylist. 

1. https://we.tl/t-ydWOmpSGr6
2. {
    "filters": [
        {
            "extra_highlighted": false,
            "extra_score": false,
            "extra_unknowns": false,
            "extra_unknowns_count": false,
            "field": "Target Word",
            "modify": true,
            "morph_priority": "es-freq.csv",
            "morphemizer_description": "spaCy: es_core_news_lg",
            "note_type": "Migaku Spanish",
            "read": true,
            "tags": {
                "exclude": [],
                "include": []
            }
        },
        {
            "extra_highlighted": false,
            "extra_score": false,
            "extra_unknowns": false,
            "extra_unknowns_count": false,
            "field": "Word",
            "modify": false,
            "morph_priority": "es-freq.csv",
            "morphemizer_description": "spaCy: es_core_news_lg",
            "note_type": "ES1K-v2-02e18",
            "read": true,
            "tags": {
                "exclude": [],
                "include": []
            }
        },
        {
            "extra_highlighted": false,
            "extra_score": false,
            "extra_unknowns": false,
            "extra_unknowns_count": false,
            "field": "Voorkant",
            "modify": true,
            "morph_priority": "es-freq.csv",
            "morphemizer_description": "spaCy: es_core_news_lg",
            "note_type": "Basis",
            "read": true,
            "tags": {
                "exclude": [],
                "include": []
            }
        }
    ],
    "preprocess_ignore_bracket_contents": true,
    "preprocess_ignore_names_morphemizer": false,
    "preprocess_ignore_names_textfile": false,
    "preprocess_ignore_round_bracket_contents": false,
    "preprocess_ignore_slim_round_bracket_contents": false,
    "preprocess_ignore_suspended_cards_content": false,
    "recalc_due_offset": 500000,
    "recalc_interval_for_known": 21,
    "recalc_move_known_new_cards_to_the_end": false,
    "recalc_number_of_morphs_to_offset": 100,
    "recalc_offset_new_cards": false,
    "recalc_on_sync": false,
    "recalc_read_known_morphs_folder": false,
    "recalc_suspend_known_new_cards": false,
    "recalc_toolbar_stats_use_known": false,
    "recalc_toolbar_stats_use_seen": true,
    "recalc_unknowns_field_shows_inflections": true,
    "recalc_unknowns_field_shows_lemmas": false,
    "shortcut_browse_all_same_unknown": "Shift+L",
    "shortcut_browse_ready_same_unknown": "L",
    "shortcut_browse_ready_same_unknown_lemma": "Ctrl+Shift+L",
    "shortcut_generators": "Ctrl+Shift+G",
    "shortcut_known_morphs_exporter": "Ctrl+Shift+E",
    "shortcut_learn_now": "Ctrl+Alt+N",
    "shortcut_recalc": "Ctrl+M",
    "shortcut_set_known_and_skip": "K",
    "shortcut_settings": "Ctrl+O",
    "shortcut_view_morphemes": "Ctrl+Alt+V",
    "skip_only_known_morphs_cards": false,
    "skip_show_num_of_skipped_cards": true,
    "skip_unknown_morph_seen_today_cards": false,
    "tag_known_automatically": "am-known-automatically",
    "tag_known_manually": "am-known-manually",
    "tag_learn_card_now": "am-learn-card-now",
    "tag_not_ready": "am-not-ready",
    "tag_ready": "am-ready"
}

**Comment by mortii** [comment]
Which deck has the problem?

![Screenshot from 2024-06-02 12-40-05](https://github.com/mortii/anki-morphs/assets/15674619/3d0fd385-b08a-458d-b5bd-192909474086)

**Comment by SalomoDavidson** [comment]
![image](https://github.com/mortii/anki-morphs/assets/61660028/839d14a5-c0b3-48f0-b61e-64d82d4d09ef)
The deck called 'Spaanse Zinnen' put I put it outside the main deck, because I wanted it to work, but then it still didn't work for me. But I see that by you that is not updated.

**Comment by SalomoDavidson** [comment]
I checked it with words like él that should show up first.
So if it works you should get this one: 
![image](https://github.com/mortii/anki-morphs/assets/61660028/bec8d8d8-ea2d-456d-809f-90c537f26342)

**Comment by mortii** [comment]
I recalced and it looks fine to me, it successfully orders the cards based on the frequency file:
![Screenshot from 2024-06-02 18-22-20](https://github.com/mortii/anki-morphs/assets/15674619/05d37d3c-b278-4241-98a8-c3b96bf62627)
![Screenshot from 2024-06-02 18-22-39](https://github.com/mortii/anki-morphs/assets/15674619/ccbe75a0-900c-4a85-a619-137226168162)
![Screenshot from 2024-06-02 18-23-26](https://github.com/mortii/anki-morphs/assets/15674619/ec876aa7-5bcc-4ead-882f-a80b4e6f9840)

The "la" card you showed has the note type "Migaku Frequentie Spaans" which you haven't selected as a note filter in the ankimorphs settings, which is why it isn't reordered by ankimorphs.
![Screenshot from 2024-06-02 18-35-47](https://github.com/mortii/anki-morphs/assets/15674619/7b94e450-f208-450c-b476-bcc8e443f05e)

**Comment by SalomoDavidson** [comment]
Thanks! I changed that, but still, when I was checking it with adding 3 extra cards to my learning schedule for today it was still not in order of frequency. First came demasiado (1463d on the list) then la (3rd) en then demonstar (2548).

**Comment by mortii** [comment]
Your problem likely stems from something else in your setup, rather than a problem with the frequency file.

Here are some leading candidates:
1. **The note type is not what you expected** - open the card info window and check that its note type matches a note filter that has `modify` enabled.
2. **The found morphs were not what you expected** - this is a common issue. Enable some of the extra fields for a better insight into this. The `am-unknows` and `am-highlighted` extra fields are particularly useful.
3. **The deck behavior is not what you expected** - having sub-decks can lead to issues, having multiple different note types in a deck can lead to issues,  changing the insertion and display order can obviously also lead to unexpected results.

If you still find some cards that you think are wrong, then send me some screenshots of the cards and the info I described above (1 and 2 are the most important).

**Comment by SalomoDavidson** [comment]
I checked 1 and 3. I did 2, what does that do exactly? and for what should I look for?


Btw, thank you very much for spending so much time on me, I appreciate it :)

**Comment by mortii** [comment]
Extra fields contains data that AnkiMorphs finds/uses, so it activating them allows for easier debugging.

Here is an example with the same card as before, and with this we can now confirm that it successfully found the morph "la":
![Screenshot from 2024-06-03 15-23-52](https://github.com/mortii/anki-morphs/assets/15674619/06535451-fd3d-4613-8a05-3e326d473ff6)

**Comment by SalomoDavidson** [comment]
I will check it out, thank you for helping :)
