### ISSUE TITLE
Note Filters & Extra Fields not match

### ISSUE THREAD

**Issue by HQYang1979** [mortii/anki-morphs#45]
![image](https://github.com/mortii/anki-morphs/assets/74698160/d5f3ce91-5df3-4c3f-9062-01c16a64206c)
I want to calc both the Word and Example fields of the same card. 
but I cannot highlight both Word and Example on the Extra Fields, right?
![image](https://github.com/mortii/anki-morphs/assets/74698160/3c59f352-7d37-40a4-b42d-d0ead680dbf6)

**Comment by HQYang1979** [comment]
And a terrible thing happens, after the setting above, one of the sentence field is replaced by the focus field, the contents on the sentence field are lost, fortunately I made a backup
![image](https://github.com/mortii/anki-morphs/assets/74698160/b5b270f4-412b-40fc-be26-c211398bc2f8)

**Comment by mortii** [comment]
Thank goodness you made a backup!

This is another result of having a bad guide and unintuitive options, sorry! I'm so deeply familiar with the intricacies of the features it often does not cross my mind that they should be clarified. I'll try to explain it better:

### Calculated difficulty
![Screenshot from 2023-11-17 16-10-45](https://github.com/mortii/anki-morphs/assets/15674619/e84f4dac-da26-4bc2-b1fe-b910cb04e70a)

The `note filter: field`, in my case `Japanese`, is the field that ankimorphs extracts text from, which is then analyzed. The card is then sorted based on the difficulty of that analyzed text.

If I were to do this:

![Screenshot from 2023-11-17 16-28-42](https://github.com/mortii/anki-morphs/assets/15674619/d36165a6-98fb-4e52-ac30-3f05c8ecf2e8)

then all the cards would first get analyzed and sorted based on the text in the `Japanese` field. Then all the same cards would again get analyzed and sorted based on the text in the `unknown-morphs` field, making the first note filter obsolete. 

So all this is to say: don't use different `note-filter: field`s for the same cards, it will make one or more of the note filters obsolete.

### Highlighting

![Screenshot from 2023-11-17 16-49-53](https://github.com/mortii/anki-morphs/assets/15674619/274a006b-d651-449d-84b0-0af6ec0d46bd)

The selected `extra fields: highlighted` field, in my case `highlighted`, takes the extracted and analyzed text from `note filter: field`, and places a highlighted version of that text into that selected `extra fields: highlighted` field. In my case it takes the text from `Japanese`, highlights it, and places in the `highlighted` field.

![Screenshot from 2023-11-17 17-05-21](https://github.com/mortii/anki-morphs/assets/15674619/8b3b6fd8-c159-4623-85c4-2d89ccfd35a9)

The selected `extra fields: highlighted` field always gets its content overwritten on recalc, so this needs to be a seperate and dedicated field, not the field that already has the text you want to analyze.

Let me know if any of that made sense or if you want me to phrase it differently.

Also, if you have any suggestions for making things more intuitive please let me know, that has been one of my biggest struggles with this project.

PS: i noticed that that I failed to upload the latest version to ankiweb. I just uploaded 0.5.3-alpha now.

**Comment by HQYang1979** [comment]
Thank you for the answer! It's just that morphman can analyze multiple fields at the same time.

**Comment by aleksejrs** [comment]
> morphman can analyze multiple fields at the same time.

I used that all the time. I have lots of mostly pre-MorphMan cloze cards that consist of multiple Text fields, and cards with context in a separate field, and alt text for image occlusion, and some comparison cards where two fields have equal weight.

**Comment by mortii** [comment]
> Thank you for the answer! It's just that morphman can analyze multiple fields at the same time.

One of the main reasons I changed it to only be one field is that I we could now have a drop down menu of the fields instead of typing them manually. I would always misspell the field name or the miss an upper-case letter and the entire filter would then be useless.

I think if you want to analyze multiple fields at the same time, the card probably fails [the minimum information principle](https://supermemo.guru/wiki/Minimum_information_principle), and you should probably change it.

Another advantage is that the "extra fields" options get massively simplified; the 'focus morph' field (now named 'unknowns') is entirely optional as a result, and the highlighting requires less setup.

**Comment by mortii** [comment]
I updated the following docs:
- [note filters usage](https://mortii.github.io/anki-morphs/user_guide/setup/settings/note-filter.html#usage)
- [extra fields](https://mortii.github.io/anki-morphs/user_guide/setup/settings/extra-fields.html)

Let me know if they are still unclear, or if there are other parts of the docs that should be improved!

**Comment by aleksejrs** [comment]
> > Thank you for the answer! It's just that morphman can analyze multiple fields at the same time.
> 
> One of the main reasons I changed it to only be one field is that we could now have a drop down menu of the fields instead of typing them manually. I would always misspell the field name or miss an upper-case letter and the entire filter would then be useless.

IIRC, such typos cause an error in MorphMan, although maybe the error happens too late.

> I think if you want to analyze multiple fields at the same time, the card probably fails [the minimum information principle](https://supermemo.guru/wiki/Minimum_information_principle), and you should probably change it.

You are assuming that all Basic cards are already "fully known field" (not analyzed) + "not fully known field" (analyzed).

I have cards like
"[picture] scarlet or crimson?"
"[picture] crimson or scarlet?"
made out of the same note. Although those kind of cards better come before the cards about the colors themselves, so it may be a bad example, because the add-on can't do anything about it.

I used to make cards like "X is father of [ ]", "X is [ ] of Y", "Y is son of [ ]", "Y is [ ] of X".

Then there are cards with questions and answers. [The full article about the minimum information principle](https://super-memory.com/articles/20rules.htm#minimum%20information%20principle) has those. The question may be easy if you make the cards yourself right before introducing them, but not if you make them in advance or download a pre-made deck (which is also likely to have a much more complex note type than the above, though I would split it).

Also, while cards mixing languages may be good for starting with a language, and are what you get from using Duolingo, they will make you mix languages.

**Comment by Vilhelm-Ian** [comment]
but why should they be on the same note. I just create seperate cards

**Comment by aleksejrs** [comment]
> but why should they be on the same note. I just create seperate cards
Have you ever edited a Basic note type to add more fields and card templates?

**Comment by Vilhelm-Ian** [comment]
Yes. If you can automate it through having multiple templates. You can automate it through a csv also

**Comment by aleksejrs** [comment]
If you make separate cards, they will not be buried as siblings, because the add-ons for that have not been updated for the V3 scheduler.

**Comment by mortii** [comment]
Almost all my cards are straightforward in nature, so it is entirely possible that I have missed important use-cases.  Let's discuss this further here: #67

**Comment by mortii** [comment]
> Having multiple input fields definitely has valid use cases. That being said I think those use cases are too narrow for the complexity it will bring to the average user, but most of all the complexity it will add to the code base.
>
>I think one of the biggest problems MorphMan has is that it is too complicated, and I don't want to the same thing to happen with AnkiMorphs.
>
>I really value honest and constructive feedback and discussions--having your ideas and solutions challenged is crucial to finding the best antifragile ideas and solutions.
>
>Thanks for providing that feedback, and apologies for not being willing to implement the feature :pray:

_Originally posted by @mortii in https://github.com/mortii/anki-morphs/discussions/67#discussioncomment-7641232_

I'll probably address this in the FAQs too.
Sorry!
