### ISSUE TITLE
Add spaCy morphemizers

### ISSUE THREAD

**Issue by mortii** [mortii/anki-morphs#62]
### Discussed in https://github.com/mortii/anki-morphs/discussions/13

<div type='discussions-op-text'>

<sup>Originally posted by **Vilhelm-Ian** September 23, 2023</sup>
For languages without spaces like german there is no dictionary So K and V are same. So morphman gives me the same word different endings. It would be nice if morphman used Spacy</div>

**Comment by Vilhelm-Ian** [comment]
Doing this with spacy is easy all you have to do is token.lemma to get the lemma. 

The hard part that I can get around is packaging spacy because of C++ dependcies like numpy to work.

For the models themselves we can go around two ways.

1. Have the user download the model and drag and drop the folder to the addon folder and then from the addon to select the model.

2. Or do something like this from the addon
subprocess.Popen('pip install -t ./path model"', shell=True)
Here is someone who tried to make it to seperate addon: https://github.com/rteabeault/AnkiSpacy

**Comment by mortii** [comment]
OMG! That addon looks perfect for our use-case (at least at first glance). That could potentially take care of a lot of work for us.  We should probably try to leverage that add-on first, if that doesn't work then maybe try something like your 1st suggestion?

Do you want to experiment with this @Vilhelm-Ian ? There are things I want to do first before I really start working on this, and if you already have some trial-and-error experience then we could potentially get it working faster.

**Comment by mortii** [comment]
Or maybe first just use any way possible to import spaCy to even test of it produces our desired outout, then we can worry about the importing later?

**Comment by Vilhelm-Ian** [comment]
Offcourse I was just throwing out ideas how it could be done

**Comment by mortii** [comment]
Brainstorming is great. We should probably start using #13 for any further discussion and trial-and-error results. This issue can just be a placeholder for the project roadmap view.

**Comment by mortii** [comment]
released in [v0.11](https://github.com/mortii/anki-morphs/releases/tag/v0.11.0-alpha)
