### ISSUE TITLE
It's not working as morphman, I'm kinda lost.

### ISSUE THREAD

**Issue by HQYang1979** [mortii/anki-morphs#71]
In morphman, when all the cards in a deck are all K'ed (known), no cards in this deck will appear again. But Ankimorph, you'll have to review all the cards even if they are known.

I think morphman is making more sense. Or am I doing it wrong?

**Comment by mortii** [comment]
All my decks are very large so I haven't encountered this kind of problem before. 

Do you think the cards should be buried, suspended, or something else?

**Comment by Vilhelm-Ian** [comment]
@HQYang1979 how should they be treated. Do you want to bury or suspend them

**Comment by HQYang1979** [comment]
Honestly I don't know, I am still learning to use morphman and ankimorph to learn languages. I am a native Mandarin and Cantonese speaker and I think pretty fluent in English and Japanese, and I am working my way up Spanish and Korean, and Russian too. Having said that, I am learning to use both addons to make a difference in my language learning journey.
I am glad to try ankimorph because the development of morphman has stopped. I think morphman is a bit more robust but who knows when it will stop working and there are still a lots to improve in morphman but now that it is in a coma.
I am not sure what to expect from ankimorph for now because as I said I am still trying to understand how the addons will fit into my learning, but definitely what morphman has been doing right must be preserved in ankimorph. And I am collecting my thoughts along the way I am using both addons.

I have great hope in ankimorph because we also have great developers @mortii @Vilhelm-Ian , I will expect ankimorph to be much more than morphman. And I am excited to promote ankimorph to my friends and other users...

**Comment by mortii** [comment]
> I am glad to try ankimorph because the development of morphman has stopped. I think morphman is a bit more robust but who knows when it will stop working and there are still a lots to improve in morphman but now that it is in a coma.
I am not sure what to expect from ankimorph for now because as I said I am still trying to understand how the addons will fit into my learning, but definitely what morphman has been doing right must be preserved in ankimorph. And I am collecting my thoughts along the way I am using both addons.

@HQYang1979 I completely agree!

I want AnkiMorphs to be as user-friendly and intuitive as possible, and you have provided amazing feedback to for us to try and make that happen, thank you so much :pray: 

If you ever think of _anything_ that would make AnkiMorphs better (robust, user-friendly, etc.) then please let us know, we all want to make that a reality!

**Comment by mortii** [comment]
Maybe wee could add a 'suspend cards with only known morphs'-option in the Recalc tab in settings? That might be an easy solution.

**Comment by mortii** [comment]
In [v0.7.0](https://github.com/mortii/anki-morphs/releases/tag/v0.7.0-alpha) there is now a ['suspend new cards with only known morphs'-option](https://mortii.github.io/anki-morphs/user_guide/setup/settings/recalc.html).
