### ISSUE TITLE
Japanese conjugation not as expected.

### ISSUE THREAD

**Issue by HQYang1979** [mortii/anki-morphs#76]
![image](https://github.com/mortii/anki-morphs/assets/74698160/4744b7b9-3cf8-455e-ba4f-99fff9f46611)

**Comment by Vilhelm-Ian** [comment]
@HQYang1979 it parses the sentence the same way morphman does. It only puts the lemmatized form in the unknown field instead of the base form. To change this is really easy. The thing is would @mortii prefer to leave it like this or to change it. At the end of the day it shouldn't really change a lot with your reviews it's mostly an aesthethic thing. To let you which word is the target morph. A different approach you can take is to enable highlithing. Which will highlight the base word

**Comment by Vilhelm-Ian** [comment]
@HQYang1979 i don't understand your complaint can you try to reword it. What do you want to happen. And why do you want it to be like that

**Comment by mortii** [comment]
> So I am thinking ankimorph is counting やめるand やめ separately. Am I right? Please let me know if I am making sense.

やめる and やめ would give: U: 1 A: 2

> When I press L, I finds only the conjugated form, in the case above, やめ, but not the non conjugated oringal form やめる.

'L' looks up the same derivative (inflected) version of the morph. I might be very familiar with やめる but I might not be familiar with やめ, so I want to only look at cards that have that version of the morph. If you were to look up every card that has a やめる derivative then that could be confusing and not very helpful in that scenario.

**Comment by HQYang1979** [comment]
> > So I am thinking ankimorph is counting やめるand やめ separately. Am I right? Please let me know if I am making sense.
> 
> やめる and やめ would give: U: 1 A: 2
> 
> > When I press L, I finds only the conjugated form, in the case above, やめ, but not the non conjugated oringal form やめる.
> 
> 'L' looks up the same derivative (inflected) version of the morph. I might be very familiar with やめる but I might not be familiar with やめ, so I want to only look at cards that have that version of the morph. If you were to look up every card that has a やめる derivative then that could be confusing and not very helpful in that scenario.

This is good enough for me. 

Another reason I would like the original form to be on the focus field is that I can copy and paste it in the original form, so that I can look it up directly on a dictionary without having to type the suffix, or paste it on the sorting field so I can do the merge card thing as shown in #82 .

**Comment by mortii** [comment]
> Another reason I would like the original form to be on the focus field is that I can copy and paste it in the original form, so that I can look it up directly on a dictionary without having to type the suffix, or paste it on the sorting field so I can do the merge card thing as shown in #82 .

I don't like the idea of using the base form as a focus morph because it is lossy, i.e. you lose the context of how the morph is used in the card. That would be taking a step backwards compared to how it is done now, in my opinion.

 As for dictionaries: when I type `もらえたら` in [jisho](https://jisho.org/search/%E3%82%82%E3%82%89%E3%81%88%E3%81%9F%E3%82%89) and in [ichi](https://ichi.moe/cl/qr/?q=%E3%82%82%E3%82%89%E3%81%88%E3%81%9F%E3%82%89&r=htr) they both give me the correct root of 貰える
